const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const core=()=>import('../scripts/cloud/core.mjs');
test('cloud claims are sealed and tamper resistant',async()=>{const {seal,unseal}=await core(),c={id:9,claim_token:'private'},s=seal(c,'secret');assert.ok(!s.includes('private'));assert.deepEqual(unseal(s,'secret'),c);assert.throws(()=>unseal(s,'other'));const b=Buffer.from(s,'base64url');b[30]^=1;assert.throws(()=>unseal(b.toString('base64url'),'secret'));});
const proposal=()=>({summary:'Correct the arithmetic in a local helper',retest:'Try the same input and verify the result',changes:[{path:'public/app.js',before:'return n+1;',after:'return n+2;'}],test:' '.repeat(90)});
test('cloud changes cannot alter protected paths or network access',async()=>{const {parseProposal}=await core();assert.ok(parseProposal(JSON.stringify(proposal())));for(const path of ['server.js','../server.js','package.json','.github/workflows/test.yml']){const p=proposal();p.changes[0].path=path;assert.throws(()=>parseProposal(JSON.stringify(p)));}const p=proposal();p.changes[0].after='fetch(secret)';assert.throws(()=>parseProposal(JSON.stringify(p)));});
test('review must expressly approve with a reason',async()=>{const {approved}=await core();assert.equal(approved('{"approved":false,"reason":"This test is not meaningful."}'),false);assert.equal(approved('{"approved":"true","reason":"The patch is sufficiently reviewed."}'),false);assert.equal(approved('{"approved":true,"reason":"The patch and regression are correct."}'),true);});
test('live verification rejects wrong commit, health, or asset body',async()=>{const {verifyLive}=await core(),commit='a'.repeat(40),body='expected',hash=crypto.createHash('sha256').update(body).digest('hex');const fake=(release,asset)=>async url=>url.includes('/api/release')?{ok:true,json:async()=>release}:{ok:true,arrayBuffer:async()=>Buffer.from(asset)};const release={ok:true,commit,deployment:'deployment-id'};assert.equal((await verifyLive(commit,{'app.js':hash},{fetcher:fake(release,body)})).deployment,'deployment-id');await assert.rejects(verifyLive(commit,{'app.js':hash},{fetcher:fake({...release,commit:'b'.repeat(40)},body)}));await assert.rejects(verifyLive(commit,{'app.js':hash},{fetcher:fake(release,'old')}));await assert.rejects(verifyLive(commit,{}, {fetcher:fake({...release,ok:false},body)}));});

test('ordinary function declarations are eligible but dynamic constructors are not',async()=>{const {parseProposal}=await core(),p=proposal();p.changes[0].before='function probe(n){return n+1;}';p.changes[0].after='function probe(n){return n+2;}';assert.ok(parseProposal(JSON.stringify(p)));p.changes[0].after='new Function("return 1")';assert.throws(()=>parseProposal(JSON.stringify(p)));});
