const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const url=process.env.ISSUE_FORM_DATABASE_URL;
test('Issue types, screenshot layout, and real browser audio attachment',{skip:!url},async()=>{
 const target=new URL(url);assert.equal(target.hostname,'127.0.0.1');assert.equal(target.pathname,'/pn_issue_form_test');
 const uploads=await fs.mkdtemp(path.join(os.tmpdir(),'pn-issue-form-'));
 Object.assign(process.env,{DATABASE_URL:url,SESSION_SECRET:'local-test-secret',ADMIN_EMAIL:'form@example.test',ADMIN_PASSWORD:'local-test-password',PGSSL:'',UPLOAD_DIR:uploads});delete process.env.RESEND_API_KEY;
 const {pool,init}=require('../db');await init();const {app}=require('../server');const server=app.listen(0);await new Promise(r=>server.once('listening',r));const base='http://localhost:'+server.address().port;
 const {chromium}=require('playwright');const browser=await chromium.launch({headless:true,args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
 try{
 const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1',permissions:['microphone'],serviceWorkers:'block'});
 const page=await context.newPage();await page.goto(base);await page.locator('#email').fill('form@example.test');await page.locator('#pw').fill('local-test-password');await page.locator('#loginBtn').click();await page.locator('#issueFab').click();await page.locator('#issueMarkupCanvas').waitFor();
 assert.deepEqual(await page.locator('#issueType option').allTextContents(),['Bug/Problem','UI Improvement','Feature Improvement Idea','New Feature Idea']);assert.equal(await page.locator('#issueShotStatus').innerText(),'');assert.equal(await page.locator('#issueStatus').innerText(),'');
 const order=await page.evaluate(()=>{const above=(a,b)=>!!(document.querySelector(a).compareDocumentPosition(document.querySelector(b))&Node.DOCUMENT_POSITION_FOLLOWING);return above('#issueFrequency','.issue-evidence')&&above('#issueMarkupCanvas','.issue-markup-toolbar')&&above('.issue-evidence','#issueSend')});assert.equal(order,true);
 await page.locator('#issueType').selectOption('ui_improvement');await page.locator('#issueRecord').click();await page.waitForFunction(()=>issueMediaRecorder?.state==='recording');await page.waitForTimeout(600);await page.locator('#issueRecord').click();await page.waitForFunction(()=>issueVoiceBlob?.size>0);
 const posted=page.waitForResponse(r=>r.url()===base+'/api/issues'&&r.request().method()==='POST');await page.locator('#issueSend').click();const response=await posted;assert.equal(response.status(),200);const id=(await response.json()).id;
 const row=(await pool.query('SELECT * FROM issue_reports WHERE id=$1',[id])).rows[0];assert.equal(row.issue_type,'ui_improvement');assert.ok(row.voice_path);assert.ok(row.screenshot_path);assert.ok((await fs.stat(path.join(uploads,path.basename(row.voice_path)))).size>0);assert.ok((await fs.stat(path.join(uploads,path.basename(row.screenshot_path)))).size>0);
 for(const type of ['bug_problem','feature_improvement','new_feature','invalid']){const response=await context.request.post(base+'/api/issues',{multipart:{description:'Synthetic type test',issue_type:type}});assert.equal(response.status(),type==='invalid'?400:200);if(type!=='invalid'){const data=await response.json();assert.equal((await pool.query('SELECT issue_type FROM issue_reports WHERE id=$1',[data.id])).rows[0].issue_type,type);}}
 await page.locator('#issueModal').waitFor({state:'hidden'});await page.locator('[data-language="es"]').click();await page.locator('#issueFab').click();await page.locator('#issueMarkupCanvas').waitFor();assert.equal(await page.locator('#issueType option').nth(1).innerText(),'Mejora de la interfaz');await page.locator('.issue-evidence').scrollIntoViewIfNeeded();await page.screenshot({path:'/tmp/pn-issue-form-es.png'});assert.equal(await page.evaluate(()=>document.querySelector('.issue-dialog').scrollWidth>document.querySelector('.issue-dialog').clientWidth),false);
 }finally{await browser.close();await new Promise(r=>server.close(r));await pool.end();await fs.rm(uploads,{recursive:true,force:true});}
});
