const test=require('node:test'),assert=require('node:assert/strict');
const {coordinates,EDITIONS,registerLocationIntelligence}=require('../location-intelligence');
test('location rollout and coordinate validation preserve excluded editions',()=>{for(const e of ['general','property','hoa','paving','concrete','contractor','roofer'])assert(EDITIONS.has(e));for(const e of ['basic','issue','roads'])assert(!EDITIONS.has(e));assert(coordinates(0,0));assert(!coordinates(91,0));assert(!coordinates(0,181));assert(!coordinates('0',0));assert(!coordinates(NaN,0));});
function fixture(product='property',found=true,historyFails=false){let calls=[],routes={};const capture={id:12,user_id:8,latitude:29,longitude:-98,subject_latitude:null,subject_longitude:null};const db={query:async(sql,args)=>{calls.push({sql,args});if(sql.startsWith('SELECT'))return {rows:found?[capture]:[]};if(sql.startsWith('UPDATE'))return {rows:[{...capture,subject_latitude:args[0],subject_longitude:args[1]}]};if(sql.startsWith('INSERT')&&historyFails)throw Error('history');return {rows:[]};},release(){}};const pool={...db,connect:async()=>db};registerLocationIntelligence({get:(p,...f)=>routes.get=f.at(-1),post:(p,...f)=>routes.post=f.at(-1)},{pool,requireAuth:()=>{},currentProduct:async()=>product});const res={code:200,status(n){this.code=n;return this;},json(v){this.body=v;return this;}};return {calls,routes,res,req:{user:{id:3},params:{id:'12'},body:{subject_latitude:0,subject_longitude:0,location_description:'North pole'}}};}
test('subject correction writes separate coordinates and atomic evidence history',async()=>{const f=fixture();await f.routes.post(f.req,f.res);assert.equal(f.res.code,200);const update=f.calls.find(x=>x.sql.startsWith('UPDATE'));assert(!/SET latitude|SET longitude/.test(update.sql));assert.deepEqual(update.args,[0,0,'North pole',12]);const detail=JSON.parse(f.calls.find(x=>x.sql.startsWith('INSERT')).args[2]);assert.equal(detail.actor_id,3);assert.equal(detail.before.subject_latitude,null);assert.equal(detail.after.subject_latitude,0);assert(f.calls.some(x=>x.sql==='COMMIT'));});
test('history failure rolls back the location correction',async()=>{const f=fixture('property',true,true);await f.routes.post(f.req,f.res);assert.equal(f.res.code,500);assert(f.calls.some(x=>x.sql==='ROLLBACK'));assert(!f.calls.some(x=>x.sql==='COMMIT'));});
test('excluded editions and unrelated records cannot read or change location',async()=>{for(const e of ['basic','issue','roads']){const f=fixture(e);await f.routes.post(f.req,f.res);assert.equal(f.res.code,403);assert.equal(f.calls.length,0);}const f=fixture('property',false);await f.routes.post(f.req,f.res);assert.equal(f.res.code,404);assert(!f.calls.some(x=>x.sql.startsWith('UPDATE')));});
test('distance and true-north bearing are correct for cardinal and coincident targets',()=>{
 const vm=require('node:vm'),source=require('node:fs').readFileSync('public/location-intelligence.js','utf8'),context={};vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function locationDistanceBearing'),source.indexOf("document.addEventListener")),context);
 const east=context.locationDistanceBearing([0,0],[0,1]);assert(Math.abs(east.meters-111194.9266)<0.01);assert.equal(east.bearing,90);
 assert.equal(context.locationDistanceBearing([0,0],[1,0]).bearing,0);assert.equal(context.locationDistanceBearing([0,0],[0,-1]).bearing,270);assert.equal(context.locationDistanceBearing([0,0],[0,0]).meters,0);
});
