const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
test('real exports retain paired and instrument details with their photos',{skip:process.env.PN_EVIDENCE_EXPORT_TEST!=='1',timeout:120000},async()=>{
 process.env.DATABASE_URL='postgresql://127.0.0.1:55491/pn_evidence_retest';process.env.PGSSL='disable';process.env.SESSION_SECRET='local-evidence-test';process.env.UPLOAD_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'pn-evidence-'));delete process.env.ANTHROPIC_API_KEY;
 const {pool,init}=require('../db');assert.equal((await pool.query('SHOW data_directory')).rows[0].data_directory,'/tmp/pn-evidence-retest/db');await init();
 const {app}=require('../server'),sharp=require('sharp'),jwt=require('jsonwebtoken'),Zip=require('pizzip');const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));let owner;
 try{
 owner=(await pool.query("INSERT INTO users(email,password_hash,role,plan,pro_type,edition_access) VALUES($1,'none','admin','pro','paving',ARRAY['paving']) RETURNING id",['evidence-'+Date.now()+'@example.invalid'])).rows[0];const cookie='pn_token='+jwt.sign({id:owner.id},process.env.SESSION_SECRET);
 const req=(url,body)=>fetch('http://127.0.0.1:'+server.address().port+url,{method:body?'POST':'GET',headers:{Cookie:cookie,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const ids=[];for(const [i,color] of ['blue','green'].entries()){fs.writeFileSync(path.join(process.env.UPLOAD_DIR,`photo${i}.jpg`),await sharp({create:{width:900,height:700,channels:3,background:color}}).jpeg().toBuffer());ids.push((await pool.query("INSERT INTO captures(user_id,photo_path,photo_title,note,address,area_tags) VALUES($1,$2,$3,$4,$5,ARRAY['Paving']) RETURNING id",[owner.id,`/uploads/photo${i}.jpg`,i?'After Photo':'Before Photo',i?'AFTER UNIQUE NOTE':'BEFORE UNIQUE NOTE','Chak 274 Hakra, پنجاب'])).rows[0].id);}
 assert.equal((await req('/api/pairs',{before_id:ids[0],after_id:ids[1]})).status,200);
 for(const format of ['pdf','docx']){const r=await req('/api/export/'+format+'?ids='+ids.join(','));assert.equal(r.status,200);const b=Buffer.from(await r.arrayBuffer());assert(b.length>1000);if(process.env.PN_EVIDENCE_OUTPUT)fs.writeFileSync(path.join(process.env.PN_EVIDENCE_OUTPUT,'paired.'+format),b);if(format==='docx'){const xml=new Zip(b).file('word/document.xml').asText();const cells=xml.match(/<w:tc>.*?<\/w:tc>/gs);assert(cells[0].includes('BEFORE UNIQUE NOTE'));assert(!cells[0].includes('AFTER UNIQUE NOTE'));assert(cells[1].includes('AFTER UNIQUE NOTE'));assert(xml.includes('پنجاب'));}}
 const reading=(await pool.query("INSERT INTO camera_readings(user_id,reading_type,photo_path,title,fields,status) VALUES($1,'gauge','/uploads/photo0.jpg','pressure gauge',$2,'saved') RETURNING id",[owner.id,JSON.stringify({notes:'Dual scale instrument. '.repeat(50),reading:'8',unit:'kg/cm²',instrument_type:'pressure gauge',equipment_name:'Pump A'})])).rows[0];
 const capture=await(await req(`/api/camera-readings/${reading.id}/library`,{})).json();assert(capture.capture_id);
 for(const format of ['pdf','docx']){const r=await req('/api/export/'+format+'?ids='+capture.capture_id);assert.equal(r.status,200);const b=Buffer.from(await r.arrayBuffer());if(process.env.PN_EVIDENCE_OUTPUT)fs.writeFileSync(path.join(process.env.PN_EVIDENCE_OUTPUT,'instrument.'+format),b);if(format==='docx'){const xml=new Zip(b).file('word/document.xml').asText();const text=xml.replace(/<[^>]+>/g,'');assert(text.includes('Instrument Type: pressure gauge'));assert(text.includes('Equipment Name: Pump A'));assert(text.indexOf('Reading: 8')<text.indexOf('Notes: Dual'));assert(xml.includes('w:b'));}}
 }finally{server.closeAllConnections();await new Promise(r=>server.close(r));await pool.end();}
});
