const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process');
const enabled=process.env.PN_PRO_RETEST==='1';
test('Pro markup reopen, crop, template, export metadata and browser rendering',{skip:!enabled,timeout:120000},async()=>{
 process.env.DATABASE_URL='postgresql://127.0.0.1:55489/pn_pro_retest';process.env.PGSSL='disable';process.env.ADMIN_EMAIL='pro-retest@example.invalid';process.env.ADMIN_PASSWORD='local-only-test';process.env.UPLOAD_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'pn-pro-retest-uploads-'));
 const {pool,init}=require('../db');const guard=await pool.query('SHOW data_directory');assert.equal(guard.rows[0].data_directory,'/tmp/pn-pro-retest/db');await init();
 const {app}=require('../server'),server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;
 const sharp=require('sharp'),PizZip=require('pizzip'),{Document,Paragraph,TextRun,Packer}=require('docx');
 try{
 const user=(await pool.query("UPDATE users SET word_template_path=NULL,word_template_name=NULL,plan='pro',pro_type='general',edition_access=ARRAY['pro'] WHERE email=$1 RETURNING id",[process.env.ADMIN_EMAIL])).rows[0];
 const image=await sharp({create:{width:800,height:600,channels:3,background:'#d4e6f1'}}).jpeg().toBuffer();fs.writeFileSync(path.join(process.env.UPLOAD_DIR,'fixture.jpg'),image);
 const capture=(await pool.query("INSERT INTO captures(user_id,photo_path,photo_title,note,address,latitude,longitude,area_tags,created_at) VALUES($1,'/uploads/fixture.jpg','Roof Evidence','RETEST NOTE','123 Test Street',29.5,-98.5,ARRAY['RetestTopic'],'2026-09-17T15:00:00Z') RETURNING *",[user.id])).rows[0];
 const login=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD})});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];
 const request=(url,body)=>fetch(base+url,{method:body?'POST':'GET',headers:{Cookie:cookie,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const overlays=[{t:'rect',x:10,y:10,w:35,h:35,color:'#ff0000',thickness:1}];assert.equal((await request('/api/captures/'+capture.id,{overlays})).status,200);
 const reopened=(await(await request('/api/captures')).json()).find(c=>c.id===capture.id);assert.deepEqual(reopened.overlays,overlays);
 const marked=await request(`/api/captures/${capture.id}/stamped?res=standard`);assert.equal(marked.status,200);const pixels=await sharp(Buffer.from(await marked.arrayBuffer())).raw().toBuffer({resolveWithObject:true});assert.ok(pixels.data.some((value,index)=>index%pixels.info.channels===0&&value>180&&pixels.data[index+1]<100),'saved red markup is rendered');
 for(const engine of ['chromium','webkit']){
 await request('/api/captures/'+capture.id,{overlays});
 const browser=await require('playwright')[engine].launch({headless:true});try{const page=await browser.newPage();await page.context().addCookies([{name:'pn_token',value:cookie.split('=')[1],url:base}]);await page.goto(base);await page.locator('#body').waitFor();
 await page.evaluate(async id=>{const c=(await(await api('/api/captures')).json()).find(x=>x.id===id);state.view='edit';renderStampEditor(c);},capture.id);
 assert.equal(await page.evaluate(()=>editorOverlays.length),1);await page.locator('[data-add=custom]').click();await page.locator('#ovText').fill('ANNOTATION TEST 123');await page.locator('[data-col="#000000"]').click();await page.locator('#stampSave').click();await page.waitForFunction(()=>!document.getElementById('stampSave').disabled);await page.locator('#stampBack').click();await page.locator(`.stampbtn[data-id="${capture.id}"]`).waitFor();assert.ok(await page.locator(`img[src*="/api/captures/${capture.id}/stamped"]`).count());
 await page.reload();await page.locator('#body').waitFor();await page.evaluate(async id=>{renderStampEditor((await(await api('/api/captures')).json()).find(x=>x.id===id));},capture.id);assert.equal(await page.evaluate(()=>editorOverlays.length),2);assert.equal(await page.evaluate(()=>editorOverlays.find(x=>x.t==='custom').text),'ANNOTATION TEST 123');
 assert.deepEqual(await page.evaluate(()=>{const c={id:1,photo_path:'/uploads/a',overlays:[{}]};return capturePhotoSrc(c).startsWith('/api/captures/1/stamped');}),true);
 }finally{await browser.close();}}
 const crop=await request(`/api/captures/${capture.id}/crop`,{x:0,y:0,w:50,h:50});assert.equal(crop.status,200,await crop.text());const cropped=(await(await request('/api/captures')).json()).find(c=>c.id===capture.id);assert.notEqual(cropped.photo_path,capture.photo_path);assert.equal(cropped.photo_width,400);assert.equal(cropped.photo_height,300);assert.ok(cropped.photo_original_path);
 const extra=[];for(let i=2;i<=3;i++)extra.push((await pool.query("INSERT INTO captures(user_id,photo_path,photo_title,note,address,latitude,longitude,area_tags,created_at) VALUES($1,$2,$3,'RETEST NOTE','123 Test Street',29.5,-98.5,ARRAY['RetestTopic'],'2026-09-17T15:00:00Z') RETURNING id",[user.id,cropped.photo_path,'Roof Evidence '+i])).rows[0].id);
 const qa=process.env.PN_PRO_QA_DIR;if(qa)fs.mkdirSync(qa,{recursive:true});
 const group=await(await request('/api/groups',{title:'Retest Report'})).json();assert.ok(group.id);assert.equal((await request(`/api/groups/${group.id}/add`,{ids:[capture.id,...extra]})).status,200);
 for(const layout of ['one_per_page','two_per_page']){
 await request('/api/groups/'+group.id,{layout:{photo_layout:layout,cover_page:false,font:'Arial'}});
 const response=await request('/api/export/docx?group='+group.id);assert.equal(response.status,200);const buffer=Buffer.from(await response.arrayBuffer());if(qa){fs.writeFileSync(path.join(qa,layout+'.docx'),buffer);const pdfResponse=await request('/api/export/pdf?group='+group.id);assert.equal(pdfResponse.status,200);fs.writeFileSync(path.join(qa,layout+'.pdf'),Buffer.from(await pdfResponse.arrayBuffer()));}const xml=new PizZip(buffer).file('word/document.xml').asText();for(const text of ['Roof Evidence','RetestTopic','29.50000','123 Test Street','2026','RETEST NOTE'])assert.ok(xml.includes(text),text);
 }
 const pdf=await request('/api/export/pdf?ids='+capture.id);assert.equal(pdf.status,200);const pdfPath=path.join(process.env.UPLOAD_DIR,'result.pdf');fs.writeFileSync(pdfPath,Buffer.from(await pdf.arrayBuffer()));const text=execFileSync('pdftotext',[pdfPath,'-'],{encoding:'utf8'});for(const value of ['RetestTopic','29.50000','123 Test Street','2026','RETEST NOTE'])assert.ok(text.includes(value),value);
 const template=await Packer.toBuffer(new Document({sections:[{children:[new Paragraph('RETEST LETTERHEAD'),new Paragraph({children:[new TextRun('{{PHOTO_'),new TextRun('NOTES_CONTENT}}')]}),new Paragraph('RETEST END')]}]}));const form=new FormData();form.append('template',new Blob([template]),'split.docx');const upload=await fetch(base+'/api/document-settings/template',{method:'POST',headers:{Cookie:cookie},body:form});assert.equal(upload.status,200,await upload.text());const exported=await request('/api/export/docx?group='+group.id);assert.equal(exported.status,200);const templateBuffer=Buffer.from(await exported.arrayBuffer());if(qa)fs.writeFileSync(path.join(qa,'template.docx'),templateBuffer);const xml=new PizZip(templateBuffer).file('word/document.xml').asText();for(const value of ['RETEST LETTERHEAD','RETEST END','Roof Evidence'])assert.ok(xml.includes(value),value);
 }finally{await new Promise(r=>server.close(r));await pool.end();}
});
