const {test}=require('node:test'),assert=require('node:assert/strict');
const {normalize,linkCapture,SCHEMA,VIEWS}=require('../property-incidents');
const context={title:'Vehicle Damage to Light Pole',incident_type:'Vehicle Impact',observed_at:'2026-10-03T12:00:00-05:00'};
test('incident context distinguishes observed time, reported time and documentary status',()=>{const d=normalize(context);assert.equal(d.observed_at,'2026-10-03T17:00:00.000Z');assert.equal(d.reported_at,null);assert.equal(d.status,'Open');assert.throws(()=>normalize({...context,observed_at:'bad'}));assert.throws(()=>normalize({...context,incident_type:'Other'}));assert.throws(()=>normalize({...context,status:'Investigating'}));assert.throws(()=>normalize({...context,skipped_views:{Identification:''}}));assert.equal(normalize({...context,skipped_views:{Identification:'No identifier present'}}).skipped_views.Identification,'No identifier present');});
test('incident linkage rejects other editions, non-photo views and inaccessible records',async()=>{const db={query:async()=>({rows:[]})},b={userId:1,companyId:1,incidentId:7,captureId:10,view:'Overview',hasPhoto:true};await assert.rejects(linkCapture(db,{...b,product:'hoa'}),/Property Manager/);await assert.rejects(linkCapture(db,{...b,product:'property',hasPhoto:false}),/photograph/);await assert.rejects(linkCapture(db,{...b,product:'property',view:'AI severity'}),/Invalid/);await assert.rejects(linkCapture(db,{...b,product:'property'}),/not found/);});
test('normal captures attach to one incident without maintenance duplication',async()=>{const queries=[],db={query:async(sql,values)=>{queries.push({sql,values});return {rows:[{id:7}]};}};await linkCapture(db,{userId:1,companyId:2,incidentId:7,captureId:10,product:'property',hasPhoto:true,view:'Damage'});assert.deepEqual(queries[0].values,[7,1,2]);assert.deepEqual(queries[1].values,[7,10,'Damage']);assert.match(SCHEMA,/capture_id INTEGER NOT NULL UNIQUE/);assert.equal(VIEWS.length,6);});

test('incident queue preserves association and upload identity through reopening',async()=>{
 const {IDBFactory}=require('fake-indexeddb'),q=require('../public/capture-queue');global.indexedDB=new IDBFactory();const account=await q.accountKey('incident@example.test');const row=await q.create({photo:new Blob(['photo']),incident_id:7,incident_view:'Damage'},false,account,'property');const [restored]=await q.all();assert.equal(restored.payload.incident_id,7);assert.equal(restored.payload.incident_view,'Damage');assert.equal(restored.requestId,row.requestId);assert(q.eligible(restored,account,'property'));await q.remove(row.id);
});
