const test=require('node:test'),assert=require('node:assert/strict'),express=require('express');
const {registerSendShortcuts,validateShortcut}=require('../send-shortcuts');
function store(){const rows=[];let id=0;return {rows,async query(sql,args){if(sql.startsWith('INSERT')){const [user_id,name,type,target,format]=args,row={id:++id,user_id,name,type,target,format};rows.push(row);return {rows:[row]};}if(sql.startsWith('SELECT'))return {rows:rows.filter(row=>row.user_id===args[0])};if(sql.startsWith('DELETE')){assert.match(sql,/id=\$1 AND user_id=\$2/);const index=rows.findIndex(row=>row.id===args[0]&&row.user_id===args[1]);return {rows:index<0?[]:rows.splice(index,1)};}throw Error('Unexpected query');}};}
test('shortcut destinations reject unsafe links and invalid formats',()=>{const row={name:'Joe',type:'email',target:'joe@example.invalid',format:'pdf'};assert(validateShortcut(row));for(const target of ['javascript:alert(1)','http://example.invalid','https://user:pass@example.invalid'])assert.equal(validateShortcut({...row,type:'website',target}),null);for(const type of ['unknown','__proto__'])assert.equal(validateShortcut({...row,type}),null);assert.equal(validateShortcut({...row,format:'exe'}),null);assert.equal(validateShortcut({...row,name:' '}),null);});
test('account API shares shortcuts across clients and rejects cross-account changes',async t=>{const app=express(),pool=store();app.use(express.json());registerSendShortcuts(app,{pool,requireAuth:(req,res,next)=>{const id=Number(req.get('X-Test-Account'));if(!id)return res.status(401).json({error:'not authenticated'});req.user={id};next();}});const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}/api/send-shortcuts`;const headers={'X-Test-Account':'1','X-Photo-Notes-Shortcuts':'1','Content-Type':'application/json'};assert.equal((await fetch(base)).status,401);const response=await fetch(base,{method:'POST',headers,body:JSON.stringify({name:'Susie',type:'email',target:'susie@example.invalid',format:'pdf'})});assert.equal(response.status,201);const row=await response.json();const second=await fetch(base,{headers:{'X-Test-Account':'1'}});assert.equal((await second.json())[0].id,row.id);assert.deepEqual(await(await fetch(base,{headers:{'X-Test-Account':'2'}})).json(),[]);assert.equal((await fetch(base+'/'+row.id,{method:'DELETE',headers:{...headers,'X-Test-Account':'2'}})).status,404);assert.equal(pool.rows.length,1);assert.equal((await fetch(base,{method:'POST',headers:{'X-Test-Account':'1','Content-Type':'application/json'},body:'{}'})).status,403);assert.equal((await fetch(base+'/'+row.id,{method:'DELETE',headers})).status,200);assert.equal(pool.rows.length,0);});
module.exports={store};

test('Ramo shortcut access requires both Concrete Pro and explicit designation',()=>{
 const {ramoShortcutAllowed}=require('../send-shortcuts');const old=process.env.RAMO_INTAKE_ALLOWED_USER_IDS;process.env.RAMO_INTAKE_ALLOWED_USER_IDS='991';
 try{assert.equal(ramoShortcutAllowed({id:991,plan:'pro',pro_type:'concrete'}),true);assert.equal(ramoShortcutAllowed({id:992,plan:'pro',pro_type:'concrete'}),false);assert.equal(ramoShortcutAllowed({id:991,plan:'pro',pro_type:'general'}),false);assert.equal(ramoShortcutAllowed({id:991,plan:'free',pro_type:'concrete'}),false);}finally{if(old===undefined)delete process.env.RAMO_INTAKE_ALLOWED_USER_IDS;else process.env.RAMO_INTAKE_ALLOWED_USER_IDS=old;}
});
test('Ramo shortcuts cannot be created or listed without designation',async t=>{
 const app=express(),pool=store();app.use(express.json());registerSendShortcuts(app,{pool,canUseRamo:u=>u.id===1,requireAuth:(req,res,next)=>{req.user={id:Number(req.get('X-Test-Account'))};next();}});
 const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}/api/send-shortcuts`;
 const headers={'X-Test-Account':'2','X-Photo-Notes-Shortcuts':'1','Content-Type':'application/json'},body=JSON.stringify({name:'Ramo',type:'ramo',target:'',format:'pdf'});
 assert.equal((await fetch(base,{method:'POST',headers,body})).status,403);assert.equal((await fetch(base,{method:'POST',headers:{...headers,'X-Test-Account':'1'},body})).status,201);
 pool.rows.push({id:99,user_id:2,type:'ramo'});assert.deepEqual(await(await fetch(base,{headers})).json(),[]);
});
