const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
test('unresolved reports: ordered documents, ticket evidence, duplicate prevention, scanner library and customer markup',{skip:process.env.PN_BUG_RETEST!=='1',timeout:120000},async()=>{
 process.env.DATABASE_URL='postgresql://127.0.0.1:55489/pn_pro_retest';process.env.PGSSL='disable';process.env.SESSION_SECRET='local-bugs-test';process.env.UPLOAD_DIR=fs.mkdtempSync(path.join(os.tmpdir(),'pn-bugs-'));delete process.env.ANTHROPIC_API_KEY;
 const {pool,init}=require('../db');assert.equal((await pool.query('SHOW data_directory')).rows[0].data_directory,'/tmp/pn-pro-retest/db');await init();
 const {app}=require('../server'),sharp=require('sharp'),jwt=require('jsonwebtoken'),PizZip=require('pizzip');const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port;let owner;
 try{
 owner=(await pool.query("INSERT INTO users(email,password_hash,role,plan,pro_type,edition_access) VALUES($1,'none','admin','pro','paving',ARRAY['paving']) RETURNING id",['bugs-'+Date.now()+'@example.invalid'])).rows[0];
 const cookie='pn_token='+jwt.sign({id:owner.id},process.env.SESSION_SECRET);
 const req=(url,body,method)=>fetch(base+url,{method:method||(body?'POST':'GET'),headers:{Cookie:cookie,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});
 const image=await sharp({create:{width:800,height:400,channels:3,background:'white'}}).jpeg().toBuffer();fs.writeFileSync(path.join(process.env.UPLOAD_DIR,'fixture.jpg'),image);
 const job=await(await req('/api/jobs',{name:'Retest paving job'})).json();assert.ok(job.id);
 const ids=[];for(let i=0;i<3;i++)ids.push((await pool.query("INSERT INTO captures(user_id,photo_path,photo_title,note,job_id,overlays) VALUES($1,'/uploads/fixture.jpg',$2,'Evidence',$3,$4) RETURNING id",[owner.id,'Photo '+i,job.id,JSON.stringify([{t:'rect',x:10,y:10,w:30,h:30,color:'#ff0000',thickness:2}])])).rows[0].id);
 const group=await(await req('/api/groups',{title:'Ordered',ids:[ids[2],ids[0],ids[1]]})).json();assert.ok(group.id);
 assert.deepEqual((await(await req('/api/groups/'+group.id)).json()).items.map(c=>c.id),[ids[2],ids[0],ids[1]]);
 const ticketIds=[];for(let i=0;i<2;i++)ticketIds.push((await pool.query("INSERT INTO asphalt_tickets(user_id,photo_path) VALUES($1,'/uploads/fixture.jpg') RETURNING id",[owner.id])).rows[0].id);
 const ticket={ticket_number:'T-44',plant_name:'Plant',ticket_date:'09/01/2026',job_id:job.id,net_tons:12};
 const saves=await Promise.all(ticketIds.map(id=>req('/api/asphalt-tickets/'+id,ticket)));assert.deepEqual(saves.map(r=>r.status).sort(),[200,409]);
 const today=await(await req('/api/asphalt-tickets?saved_from='+encodeURIComponent(new Date(Date.now()-60000).toISOString())+'&saved_to='+encodeURIComponent(new Date(Date.now()+60000).toISOString()))).json();assert.equal(today.tickets.length,1);assert.equal(today.total_tons,12);assert.equal(today.tickets[0].job_id,job.id);assert.ok(String(today.tickets[0].ticket_date).startsWith('2026-09-01'));
 const report=await req('/api/paving/jobs/'+job.id+'/report?doc=docx');assert.equal(report.status,200);const zip=new PizZip(Buffer.from(await report.arrayBuffer()));assert.ok(zip.file('word/document.xml').asText().includes('T-44'));assert.equal((zip.file('word/document.xml').asText().match(/<w:drawing>/g)||[]).length,4,'three job photos plus ticket evidence');
 const pair=await(await req('/api/pairs',{before_id:ids[0],after_id:ids[1],comparison_opacity:.35})).json();assert.ok(pair.pair.id);assert.equal(Number(pair.pair.comparison_opacity),.35);
 assert.equal((await req('/api/pairs/'+pair.pair.id+'/comparison')).status,200);
 const pairWord=await req('/api/export/docx?ids='+ids.slice(0,2).join(','));const pairXml=new PizZip(Buffer.from(await pairWord.arrayBuffer())).file('word/document.xml').asText();assert.ok(pairXml.includes('Before and after comparison'));assert.equal((pairXml.match(/<w:drawing>/g)||[]).length,1);
 const approval=await(await req('/api/approvals',{ids:[ids[0]],title:'Review'})).json();const html=await(await fetch(base+'/review/'+approval.token)).text();assert.ok(html.includes('/photos/'+ids[0]));
 const marked=await fetch(base+'/review/'+approval.token+'/photos/'+ids[0]);assert.equal(marked.status,200);const pixels=await sharp(Buffer.from(await marked.arrayBuffer())).raw().toBuffer({resolveWithObject:true});assert.ok(pixels.data.some((x,i)=>i%pixels.info.channels===0&&x>180&&pixels.data[i+1]<100));assert.equal((await fetch(base+'/review/'+approval.token+'/photos/'+ids[1])).status,404);
 const reading=(await pool.query("INSERT INTO camera_readings(user_id,reading_type,photo_path,title,fields,status) VALUES($1,'plan_sketch','/uploads/fixture.jpg','Plan',$2,'saved') RETURNING id",[owner.id,JSON.stringify({visible_notes:'Every field is retained',sheet_number:'A1'})])).rows[0];
 const added=await(await req('/api/camera-readings/'+reading.id+'/library',{},'POST')).json();assert.ok(added.capture_id);assert.equal((await(await req('/api/camera-readings/'+reading.id+'/library',{},'POST')).json()).capture_id,added.capture_id);
 const capture=(await pool.query('SELECT * FROM captures WHERE id=$1',[added.capture_id])).rows[0];assert.ok(capture.note.includes('Every field is retained'));assert.equal(capture.photo_title,'Plan');
 assert.equal((await req('/api/camera-readings/'+reading.id,null,'DELETE')).status,200);assert.equal((await pool.query('SELECT id FROM captures WHERE id=$1',[added.capture_id])).rowCount,1);
 // Real browser interactions verify batch-document changes, persisted crop filter, map drawing and template preview.
 const browser=await require('playwright').chromium.launch({headless:true});try{
 const page=await browser.newPage({viewport:{width:1200,height:900}});page.on('console',m=>{if(m.type()==='error')console.log('browser:',m.text());});page.on('pageerror',e=>console.log('browser error:',e.message));await page.context().addCookies([{name:'pn_token',value:cookie.split('=')[1],url:base}]);await page.goto(base,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>typeof state!=='undefined'&&state.me);await page.locator('#body').waitFor();
 const sharedBytes=await page.evaluate(async bytes=>Array.from(new Uint8Array(await(await PhotoNotesShareImage.withDetails(new File([new Uint8Array(bytes)],'source.jpg',{type:'image/jpeg'}),'123 Main Street\nPhoto note and date')).arrayBuffer())),Array.from(image));
 const sharedMeta=await sharp(Buffer.from(sharedBytes)).metadata();assert.equal(sharedMeta.width,800);assert.ok(sharedMeta.height>400);
 await page.evaluate(()=>{localStorage.setItem('pn_install_prompt_dismissed_v1','dismissed');state.plan='free';state.view='capture';renderApp();window._speech=[];window.SpeechRecognition=class{constructor(){window._speech.push(this);}start(){}stop(){this.onend?.();}};isIOS=()=>true;state.photoFile=new File(['fixture'],'fixture.jpg',{type:'image/jpeg'});saveCapture=async()=>true;});
 await page.locator('#note').fill('Typed note');await page.click('#dictate');await page.evaluate(()=>_speech.at(-1).onresult({results:[[{transcript:'spoken note'}]]}));await page.locator('#note').fill('Replacement');await page.evaluate(()=>_speech.at(-1).onresult({results:[[{transcript:'old words'}]]}));assert.equal(await page.inputValue('#note'),'Replacement');
 await page.click('#dictate');await page.evaluate(()=>_speech.at(-1).onend());await page.waitForFunction(()=>_speech.length===3);await page.evaluate(()=>_speech.at(-1).onresult({results:[[{transcript:'after pause'}]]}));assert.ok((await page.inputValue('#note')).includes('after pause'));await page.click('#dictate');
 await page.click('#send');await page.locator('#captureShareDialog').waitFor();assert.equal(await page.locator('#captureShareDialog').evaluate(e=>getComputedStyle(e).position),'fixed');await page.click('#captureShareDialog [data-close]');await page.click('#send');await page.locator('#captureShareDialog').waitFor();assert.equal(await page.locator('#captureShareDialog').count(),1);await page.evaluate(()=>{state.view='my-issues';renderApp();});assert.equal(await page.locator('#captureShareDialog').count(),0);
 await page.evaluate(()=>{state.plan='pro';state.proType='paving';});
 await page.evaluate(()=>{state.view='organize';renderList();});await page.locator('#batchDocument option').nth(1).waitFor({state:'attached'});await page.evaluate(id=>state.selectedIds=new Set([String(id)]),added.capture_id);await page.selectOption('#batchDocument',String(group.id));await page.click('#runBatch');await page.waitForFunction(()=>!document.getElementById('runBatch').disabled);assert.ok((await(await req('/api/groups/'+group.id)).json()).items.some(c=>c.id===added.capture_id));
 await page.evaluate(()=>{state.areas=['Retest'];state.editTopic='Retest';state.view='edit';renderEdit();});assert.equal(await page.inputValue('#filter'),'Retest');
 await page.evaluate(()=>{state.view='map';renderMap();});await page.locator('#drawArea').waitFor();await page.click('#drawArea');await page.locator('#mapdiv').click({position:{x:160,y:150}});assert.equal(await page.evaluate(()=>window._draw.points.length),1);
 const {Document,Paragraph,Packer}=require('docx'),template=await Packer.toBuffer(new Document({sections:[{children:[new Paragraph('UNIQUE TEMPLATE HEADING'),new Paragraph('{{TITLE}}'),new Paragraph('{{PHOTO_NOTES_CONTENT}}')]}]}));const form=new FormData();form.append('template',new Blob([template]),'test.docx');assert.equal((await fetch(base+'/api/document-settings/template',{method:'POST',headers:{Cookie:cookie},body:form})).status,200);
 await page.evaluate(id=>{document.getElementById('body').innerHTML='<div id="previewTest"></div>';PhotoNotesWordPreview.render(document.getElementById('previewTest'),id);},group.id);
 try{await page.frameLocator('.word-template-preview').getByText('UNIQUE TEMPLATE HEADING',{exact:true}).waitFor({timeout:10000});}catch(e){console.log('preview:',await page.frameLocator('.word-template-preview').locator('body').innerText());throw e;}assert.equal(await page.frameLocator('.word-template-preview').getByText('Ordered',{exact:true}).count(),1);
 }finally{await browser.close();}
 }catch(e){console.error(e.stack);throw e;}finally{server.closeAllConnections();await new Promise(r=>server.close(r));await pool.end();}
});
