const test=require('node:test'),assert=require('node:assert/strict');
const analyzer=require('../concrete-analyzer');
const valid=()=>({element:'slab',condition:'monitor',severity:'minor',confidence:'medium',observation:'Visible crack and chipped edge.',findings:[{type:'cracking',observation:'Crack across surface.',confidence:'high'},{type:'chipped_edge',observation:'Localized edge loss.',confidence:'medium'}]});
test('Concrete validates multiple findings using existing app vocabulary',()=>{const d=analyzer.normalize(valid());assert.equal(d.findings.length,2);assert.equal(d.element,'slab');assert.equal(d.severity,'minor');assert.equal(Object.keys(analyzer.elements).length,12);});
test('invalid enums, contradictory findings and oversized observations fail closed',()=>{for(const edit of [d=>d.element='roof',d=>d.condition='spalling',d=>d.severity='high',d=>d.confidence=0.9,d=>d.findings=[],d=>d.observation='x'.repeat(601),d=>d.findings[1].type='no_obvious_defect']){const d=valid();edit(d);assert.throws(()=>analyzer.normalize(d));}});
test('AI cannot assert unsafe or critical; explicit human review can retain existing values',()=>{const d=valid();d.condition='unsafe';d.severity='critical';assert.throws(()=>analyzer.normalize(d));assert.equal(analyzer.normalize(d,{review:true}).condition,'unsafe');});
test('normalization excludes unsupported location, mix, dimensions and recommendations',()=>{const d=analyzer.normalize({...valid(),location:'guessed',psi:4000,width:10,repair:'replace'});assert.equal(d.location,undefined);assert.equal(d.psi,undefined);assert.equal(d.width,undefined);assert.equal(d.repair,undefined);});
test('Paving classifier retains its transport, prompt vocabulary, normalization and provenance',async()=>{
 const fs=require('node:fs'),vm=require('node:vm'),source=fs.readFileSync(require('node:path').join(__dirname,'../server.js'),'utf8');const start=source.indexOf('async function classifyCapture('),end=source.indexOf("app.post('/api/captures/:id/classify'",start);let updates=[],prompt;
 const raw={defect_type:'pothole',severity:'high',confidence:'medium',rationale:'Visible pavement loss.'};let data=raw;
 const context={pool:{query:async(sql,args)=>sql.startsWith('SELECT')?{rows:[{id:1,photo_path:'/photo'}]}:(updates.push(args),{rows:[{id:1,defect_type:args[0],defect_severity:args[1],defect_confidence:args[2],defect_ai:JSON.parse(args[3]),defect_user_confirmed:false}]})},localPhoto:p=>p,visionJSON:async(p,text)=>{prompt=text;return {data,error:data?null:'billing'};},visionFeedback:r=>({ai_error:r.error}),DEFECT_TYPES:['pothole','none','other'],SEVERITIES:['low','medium','high'],logEvent:()=>{}};
 vm.createContext(context);vm.runInContext(source.slice(start,end),context);const r=await context.classifyCapture(9,1);assert.equal(r.capture.defect_type,'pothole');assert.equal(r.capture.defect_severity,'high');assert.equal(r.capture.defect_user_confirmed,false);assert.deepEqual(r.capture.defect_ai,raw);assert.match(prompt,/alligator_cracking, transverse_cracking, longitudinal_cracking/);assert.match(prompt,/base_failure, other, none/);assert.equal(updates[0][5],9);
 data=null;const failure=await context.classifyCapture(9,1);assert.equal(failure.ai_error,'billing');assert.equal(updates.length,1);
});
test('full server wires shared routes, schema and reviewed-only report/search observations',()=>{
 const fs=require('node:fs'),path=require('node:path'),read=name=>fs.readFileSync(path.join(__dirname,'..',name),'utf8');const server=read('server.js');assert.equal((server.match(/registerVisualAnalysis\(app/g)||[]).length,1);assert.match(read('db.js'),/visual-analysis'\).SCHEMA/);assert.match(server,/capture\.concrete_reviewed_observation&&`User Reviewed visual observation:/);assert.match(server,/row\.concrete_reviewed_observation&&`User Reviewed visual observation:/);assert.match(server,/COALESCE\(c\.concrete_reviewed_observation,''\) ILIKE/);
});
