const test=require('node:test');
const assert=require('node:assert/strict');
const {randomUUID,createHash}=require('node:crypto');
const fs=require('node:fs/promises');
const os=require('node:os');
const path=require('node:path');
const database=process.env.PN_WEB_TEST_DATABASE_URL;
test('Web capture retries, transaction rollback, and edition/account boundaries against PostgreSQL',{skip:!database,timeout:120000},async t=>{
 const url=new URL(database);assert.equal(url.hostname,'127.0.0.1');assert.equal(url.port,'55487');assert.equal(url.pathname,'/pn_ios_test');
 const guard=new (require('pg').Client)({connectionString:database});await guard.connect();const actual=(await guard.query('SHOW data_directory')).rows[0].data_directory;assert.equal(await fs.realpath(actual),await fs.realpath(process.env.PN_WEB_TEST_DATA_DIR));await guard.end();
 process.env.DATABASE_URL=database;process.env.PGSSL='disable';process.env.ADMIN_EMAIL='ios-integration@example.invalid';process.env.ADMIN_PASSWORD='local-test-only';
 process.env.UPLOAD_DIR=await fs.mkdtemp(path.join(os.tmpdir(),'pn-ios-uploads-'));
 const {pool,init}=require('../db');await init();await pool.query('ALTER TABLE capture_upload_receipts DROP CONSTRAINT IF EXISTS ios_test_receipt_failure');
 const {app}=require('../server');const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;
 try{
  const first=(await pool.query('SELECT id FROM users WHERE email=$1',[process.env.ADMIN_EMAIL])).rows[0].id;
  await pool.query("UPDATE users SET plan='free',pro_type='general',edition_access=ARRAY['basic','pro'] WHERE id=$1",[first]);
  const login=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:process.env.ADMIN_EMAIL,password:'local-test-only'})});assert.equal(login.status,200);const cookie=login.headers.get('set-cookie').split(';')[0];
  const send=async(key,note='Same capture',edition='basic',auth=cookie,email=process.env.ADMIN_EMAIL)=>{const body=new FormData();body.append('note',note);body.append('kind','note');body.append('photo',new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jIhoAAAAASUVORK5CYII=','base64')],{type:'image/png'}),'test.png');return fetch(base+'/api/captures',{method:'POST',headers:{Cookie:auth,'X-Photo-Notes-Capture-Id':key,'X-Photo-Notes-Edition':edition,'X-Photo-Notes-Account':createHash('sha256').update(email).digest('hex')},body});};
  await t.test('concurrent retries return one committed capture',async()=>{const key=randomUUID();const responses=await Promise.all(Array.from({length:16},()=>send(key)));for(const r of responses)assert.equal(r.status,200);const values=await Promise.all(responses.map(r=>r.json()));assert.equal(new Set(values.map(v=>v.id)).size,1);assert.equal((await pool.query('SELECT count(*)::int n FROM capture_upload_receipts WHERE request_id=$1',[key])).rows[0].n,1);assert.equal((await send(key,'Changed content')).status,409);});
  await t.test('failed receipt commit rolls back the capture and history',async()=>{const key=randomUUID(),note='Must roll back '+key;await pool.query(`ALTER TABLE capture_upload_receipts ADD CONSTRAINT ios_test_receipt_failure CHECK(request_id <> '${key}'::uuid)`);const result=await send(key,note);assert.equal(result.status,500);assert.equal((await pool.query("SELECT count(*)::int n FROM captures WHERE note=$1",[note])).rows[0].n,0);await pool.query('ALTER TABLE capture_upload_receipts DROP CONSTRAINT ios_test_receipt_failure');assert.equal((await send(key,note)).status,200);});
  await t.test('wrong edition and revoked access never create captures',async()=>{assert.equal((await send(randomUUID(),'Wrong edition','pro')).status,409);await pool.query("UPDATE users SET edition_access=ARRAY['pro'] WHERE id=$1",[first]);assert.equal((await send(randomUUID(),'Revoked','basic')).status,403);await pool.query("UPDATE users SET edition_access=ARRAY['basic','pro'] WHERE id=$1",[first]);});
  await t.test('receipt keys are isolated by authenticated account',async()=>{const second=(await pool.query("INSERT INTO users(email,name,password_hash,plan,pro_type,edition_access) SELECT 'ios-second@example.invalid','Second Tester',password_hash,'free','general',ARRAY['basic'] FROM users WHERE id=$1 ON CONFLICT(email) DO UPDATE SET active=true RETURNING id",[first])).rows[0].id;const key=randomUUID();const one=await (await send(key,'Account one')).json();const login2=await fetch(base+'/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'ios-second@example.invalid',password:'local-test-only'})});const cookie2=login2.headers.get('set-cookie').split(';')[0];const two=await (await send(key,'Account two','basic',cookie2,'ios-second@example.invalid')).json();assert.notEqual(one.id,two.id);assert.equal(two.user_id,second);assert.equal((await send(randomUUID(),'Must not cross accounts','basic',cookie2)).status,403);assert.equal((await send(randomUUID(),'No login','basic','')).status,401);});
 }finally{await new Promise(r=>server.close(r));await pool.end();await fs.rm(process.env.UPLOAD_DIR,{recursive:true,force:true});}
});
