const TYPES={plan_sketch:'Plan or Sketch',business_card:'Business Card',equipment_plate:'Equipment Plate',material_label:'Material Label',gauge:'Gauge & Instrument',paving_ticket:'Paving Delivery Ticket'};
const LABELS={product_name:'Product Name',product_code:'Product Code',lot_number:'Lot Number',quantity:'Quantity',manufactured_date:'Manufactured Date',expiration_date:'Expiration Date',instructions:'Visible Instructions',warnings:'Visible Warnings',instrument_type:'Instrument Type',reading:'Displayed Reading',unit:'Unit',equipment_name:'Equipment Name or Number',observed_at:'Displayed Date or Time',notes:'Reading Notes',manufacturer:'Manufacturer',model:'Model',serial_number:'Serial Number',year:'Year',equipment_type:'Equipment Type',specifications:'Other Specifications',name:'Name',job_title:'Job Title',company:'Company',phone:'Phone',email:'Email',address:'Address',website:'Website',project_name:'Project Name',site_address:'Site Address',sheet_title:'Sheet Title',sheet_number:'Sheet Number',revision_date:'Revision Date',scale:'Printed Scale',visible_dimensions:'Visible Dimensions',visible_notes:'Visible Notes'};
const escapeCard=v=>String(v||'').replace(/\\/g,'\\\\').replace(/\r\n|\r|\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
function vcard(row){const f=row.fields||{},lines=['BEGIN:VCARD','VERSION:3.0','FN:'+escapeCard(f.name||row.title||'Contact')];for(const [key,tag] of [['company','ORG'],['job_title','TITLE'],['phone','TEL'],['email','EMAIL'],['website','URL']])if(f[key])lines.push(tag+':'+escapeCard(f[key]));if(f.address)lines.push('ADR:;;'+escapeCard(f.address)+';;;;');const notes=Object.entries(f).filter(([k,v])=>v&&!['name','company','job_title','phone','email','website','address'].includes(k)).map(([k,v])=>(LABELS[k]||k)+': '+v).join('\n');if(notes)lines.push('NOTE:'+escapeCard(notes));return lines.concat('END:VCARD','').join('\r\n');}
function register(app,{pool,requireAuth,PDFDocument,Document,Packer,Paragraph,TextRun,ImageRun,localPhoto,renderForEmbedStamped,fittedWordImage}){
 app.get(['/api/camera-readings/:id/report','/api/asphalt-tickets/:id/report'],requireAuth,async(req,res)=>{try{
  const ticket=req.path.includes('/asphalt-tickets/');
  const row=(await pool.query(`SELECT * FROM ${ticket?'asphalt_tickets':'camera_readings'} WHERE id=$1 AND user_id=$2 AND status='saved'`,[Number(req.params.id),req.user.id])).rows[0];if(!row)return res.sendStatus(404);
  if(ticket){row.reading_type='paving_ticket';row.title='Ticket '+(row.ticket_number||row.id);row.fields=Object.fromEntries(Object.entries(row).filter(([k])=>!['id','user_id','reading_type','title','photo_path','raw_ai','confidence','status','created_at','updated_at','capture_id'].includes(k)));}
  const format=req.query.format||'pdf';if(!TYPES[row.reading_type]||!['pdf','docx','vcf'].includes(format)||(format==='vcf'&&row.reading_type!=='business_card'))return res.status(400).json({error:'Unsupported report format'});
  const name='scanner-record-'+row.id+'.'+format;res.setHeader('Content-Disposition',`attachment; filename="${name}"`);res.setHeader('Cache-Control','private, no-store');
  if(format==='vcf'){res.type('text/vcard').send(vcard(row));return;}
  const title=row.title||TYPES[row.reading_type]+' Record',details=[`Record type: ${TYPES[row.reading_type]}`,`Saved: ${new Date(row.updated_at||row.created_at).toISOString()}`,...Object.entries(row.fields||{}).filter(([,v])=>v!==null&&v!==undefined&&String(v)!=='').map(([k,v])=>`${LABELS[k]||k.replaceAll('_',' ')}: ${v}`),'Saved information is user reviewed. The source photograph is the evidence.'];
  const image=localPhoto(row.photo_path),rendered=image?await renderForEmbedStamped(image,'standard','jpeg',{}):null;
  if(format==='pdf'){res.type('application/pdf');const doc=new PDFDocument({margin:48});doc.pipe(res);doc.font(require('./pdf-evidence').fontPath);doc.fontSize(20).fillColor('#000').text(title,{align:'left'});doc.moveDown();if(rendered){doc.image(rendered.buffer,{fit:[500,300]});doc.y+=310;}doc.fontSize(11);for(const line of details){doc.text(line,{align:'left'});doc.moveDown(.4);}doc.end();return;}
  const children=[new Paragraph({children:[new TextRun({text:title,bold:true,size:32,font:'Arial',color:'000000'})]})];if(rendered)children.push(new Paragraph({children:[new ImageRun({type:'jpg',data:rendered.buffer,transformation:await fittedWordImage(rendered.buffer,500,300)})]}));for(const line of details)children.push(new Paragraph({children:[new TextRun({text:line,font:'Arial',color:'000000'})]}));res.type('application/vnd.openxmlformats-officedocument.wordprocessingml.document').send(await Packer.toBuffer(new Document({sections:[{children}]})));
 }catch(e){console.error('[scanner-report]',e.message);if(!res.headersSent)res.status(500).json({error:'Report could not be created'});}});
}
module.exports={register,vcard};
