const multer=require('multer'),sharp=require('sharp'),PDFDocument=require('pdfkit');
const {EDITIONS,editionAccess}=require('./editions');
const STATES=['not_tested','passed','failed','blocked'];
function fail(message,status=400){throw Object.assign(new Error(message),{status});}
function str(v,max=4000){if(typeof v!=='string'||v.length>max)fail('Invalid text');return v.trim();}
function validateDraft(b){
 const title=str(b.title,200),title_es=str(b.title_es||'',200),summary=str(b.summary||'',4000),summary_es=str(b.summary_es||'',4000);
 if(!title||!EDITIONS[b.edition])fail('Enter a title and select a version');
 if(!Array.isArray(b.steps)||!b.steps.length||b.steps.length>50)fail('Add between 1 and 50 test steps');
 const ids=new Set();const steps=b.steps.map((s,i)=>{if(!s||typeof s!=='object')fail('Invalid step');const id=String(s.id||`step-${i+1}`);if(!/^[a-zA-Z0-9_-]{1,80}$/.test(id)||ids.has(id)||['__proto__','constructor','prototype'].includes(id))fail('Step IDs must be unique');ids.add(id);const title=str(s.title,200),instruction=str(s.instruction,4000);if(!title||!instruction)fail('Every step needs a title and instructions');return {id,title,instruction,title_es:str(s.title_es||'',200),instruction_es:str(s.instruction_es||'',4000)};});
 if(!Array.isArray(b.assignee_ids)||b.assignee_ids.length>100||b.assignee_ids.some(id=>!Number.isInteger(id)||id<1))fail('Select valid testers');
 return {title,title_es,summary,summary_es,edition:b.edition,steps,assignee_ids:[...new Set(b.assignee_ids)]};
}
function validateResults(a,b){
 if(!b.results||typeof b.results!=='object'||Array.isArray(b.results))fail('Invalid test results');const allowed=new Set(a.steps.map(s=>s.id)),results={};
 for(const [id,r] of Object.entries(b.results)){if(!allowed.has(id)||!r||!STATES.includes(r.status))fail('Invalid test step or result');results[id]={status:r.status,notes:str(r.notes||'',4000)};}
 return {results,tester_notes:str(b.tester_notes||'',4000),device:str(b.device||'',500)};
}
function counts(a){const c={not_tested:0,passed:0,failed:0,blocked:0};for(const s of a.steps)c[a.results?.[s.id]?.status||'not_tested']++;return c;}
async function initTestingHub(pool){
 await pool.query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS is_testing_manager boolean NOT NULL DEFAULT false;
 CREATE TABLE IF NOT EXISTS testing_templates(id serial PRIMARY KEY,seed_key text UNIQUE,title text NOT NULL,title_es text NOT NULL DEFAULT '',summary text NOT NULL DEFAULT '',summary_es text NOT NULL DEFAULT '',edition text NOT NULL,steps jsonb NOT NULL,assignee_ids jsonb NOT NULL DEFAULT '[]',status text NOT NULL DEFAULT 'draft',revision integer NOT NULL DEFAULT 0,created_at timestamptz DEFAULT now(),published_at timestamptz);
 ALTER TABLE testing_assignments ADD COLUMN IF NOT EXISTS template_id integer REFERENCES testing_templates(id),ADD COLUMN IF NOT EXISTS title_es text NOT NULL DEFAULT '',ADD COLUMN IF NOT EXISTS summary_es text NOT NULL DEFAULT '',ADD COLUMN IF NOT EXISTS edition text,ADD COLUMN IF NOT EXISTS results jsonb NOT NULL DEFAULT '{}',ADD COLUMN IF NOT EXISTS device text NOT NULL DEFAULT '',ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 0,ADD COLUMN IF NOT EXISTS seen_at timestamptz,ADD COLUMN IF NOT EXISTS review_status text NOT NULL DEFAULT 'pending',ADD COLUMN IF NOT EXISTS review_notes text NOT NULL DEFAULT '';
 CREATE UNIQUE INDEX IF NOT EXISTS testing_assignment_template_user ON testing_assignments(template_id,user_id);
 CREATE TABLE IF NOT EXISTS testing_evidence(id serial PRIMARY KEY,assignment_id integer NOT NULL REFERENCES testing_assignments(id) ON DELETE CASCADE,step_id text NOT NULL,photo bytea NOT NULL,created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS testing_submissions(id serial PRIMARY KEY,assignment_id integer NOT NULL REFERENCES testing_assignments(id) ON DELETE CASCADE,snapshot jsonb NOT NULL,created_at timestamptz DEFAULT now());
 ALTER TABLE issue_reports ADD COLUMN IF NOT EXISTS testing_assignment_id integer REFERENCES testing_assignments(id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS testing_step_id text;
 CREATE INDEX IF NOT EXISTS issue_testing_assignment_idx ON issue_reports(testing_assignment_id);`);
 const seed=require('./testing-road-draft.json');
 const users=(await pool.query('SELECT id,name FROM users WHERE active=true')).rows;
 const candidates=users.map(u=>({...u,first:(u.name||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().split(/\s+/)[0]}));
 const suggested=[['jose'],['gabby','gaby']].flatMap(names=>{const matches=candidates.filter(u=>names.includes(u.first));return matches.length===1?[matches[0].id]:[];});
 await pool.query(`INSERT INTO testing_templates(seed_key,title,title_es,summary,summary_es,edition,steps,assignee_ids) VALUES('road-reporter-initial',$1,$2,$3,$4,'roads',$5,$6) ON CONFLICT(seed_key) DO NOTHING`,[seed.title,seed.title_es,seed.summary,seed.summary_es,JSON.stringify(seed.steps),JSON.stringify(suggested)]);
}
function registerTestingHub(app,{pool,requireAuth,requireAdmin}){
 const canManage=user=>user.role==='admin'||user.is_testing_manager===true;
 const requireTestingManager=(req,res,next)=>requireAuth(req,res,()=>canManage(req.user)?next():res.status(403).json({error:'Testing manager access required'}));
 const route=fn=>async(req,res)=>{try{await fn(req,res);}catch(e){if(!e.status)console.error('[testing hub]',e);res.status(e.status||500).json({error:e.status?e.message:'Testing request failed. Your unsaved work is retained on this device.'});}};
 const tx=async fn=>{const c=await pool.connect();try{await c.query('BEGIN');const r=await fn(c);await c.query('COMMIT');return r;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}};
 async function owned(c,id,user,lock=false){const a=(await c.query(`SELECT * FROM testing_assignments WHERE id=$1 AND user_id=$2${lock?' FOR UPDATE':''}`,[id,user])).rows[0];if(!a)fail('Assignment not found',404);return a;}
 async function enrich(rows){if(!rows.length)return [];const ids=rows.map(a=>a.id);const evidence=(await pool.query('SELECT id,assignment_id,step_id,created_at FROM testing_evidence WHERE assignment_id=ANY($1::int[]) ORDER BY id',[ids])).rows;const issues=(await pool.query('SELECT id,testing_assignment_id,testing_step_id,issue_type,management_status,description,fix_summary,retest_instructions FROM issue_reports WHERE testing_assignment_id=ANY($1::int[]) ORDER BY id',[ids])).rows;return rows.map(a=>({...a,counts:counts(a),evidence:evidence.filter(e=>e.assignment_id===a.id),issues:issues.filter(i=>i.testing_assignment_id===a.id)}));}
 app.get('/api/testing/assignments/mine',requireAuth,route(async(req,res)=>{res.json(await enrich((await pool.query('SELECT * FROM testing_assignments WHERE user_id=$1 ORDER BY created_at DESC,id DESC',[req.user.id])).rows));}));
 app.get('/api/testing/attention',requireAuth,route(async(req,res)=>{res.json((await pool.query("SELECT count(*) FILTER(WHERE seen_at IS NULL AND status<>'submitted')::int AS new_count,count(*) FILTER(WHERE status<>'submitted')::int AS open_count FROM testing_assignments WHERE user_id=$1",[req.user.id])).rows[0]);}));
 app.post('/api/testing/assignments/:id/seen',requireAuth,route(async(req,res)=>{await owned(pool,req.params.id,req.user.id);await pool.query('UPDATE testing_assignments SET seen_at=COALESCE(seen_at,now()) WHERE id=$1 AND user_id=$2',[req.params.id,req.user.id]);res.json({ok:true});}));
 app.post('/api/testing/assignments/:id/progress',requireAuth,route(async(req,res)=>{const result=await tx(async c=>{const a=await owned(c,req.params.id,req.user.id,true);if(a.status==='submitted')fail('Assignment is submitted. Ask a testing manager to reopen it.',409);if(req.body.revision!==a.revision)fail('This assignment changed in another window. Reload and compare your saved local draft before retrying.',409);const b=validateResults(a,req.body);return (await c.query("UPDATE testing_assignments SET results=$1,tester_notes=$2,device=$3,revision=revision+1,status='in_progress',started_at=COALESCE(started_at,now()),updated_at=now() WHERE id=$4 RETURNING *",[JSON.stringify(b.results),b.tester_notes,b.device,a.id])).rows[0];});res.json(result);}));
 app.post('/api/testing/assignments/:id/submit',requireAuth,route(async(req,res)=>{res.json(await tx(async c=>{const a=await owned(c,req.params.id,req.user.id,true);if(a.status==='submitted')return a;if(req.body.revision!==a.revision)fail('Save the latest results before submitting',409);if(!a.device)fail('Enter the device and browser used');for(const s of a.steps){const r=a.results[s.id];if(['failed','blocked'].includes(r?.status)&&!r.notes)fail('Explain each failed or blocked step in its notes');}if(counts(a).not_tested&&!a.tester_notes)fail('Explain untested steps in your overall notes');const row=(await c.query("UPDATE testing_assignments SET status='submitted',submitted_at=now(),review_status='pending',revision=revision+1,updated_at=now() WHERE id=$1 RETURNING *",[a.id])).rows[0];await c.query('INSERT INTO testing_submissions(assignment_id,snapshot) VALUES($1,$2)',[a.id,JSON.stringify(row)]);return row;}));}));
 const photoUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:8*1024*1024,files:1}}).single('photo');
 app.post('/api/testing/assignments/:id/evidence/:step',requireAuth,(req,res,next)=>photoUpload(req,res,e=>e?res.status(400).json({error:'Choose one image up to 8 MB'}):next()),route(async(req,res)=>{
  if(!req.file)fail('Choose a photo');let photo;try{photo=await sharp(req.file.buffer,{limitInputPixels:25000000}).rotate().resize({width:1800,height:1800,fit:'inside',withoutEnlargement:true}).jpeg({quality:85}).toBuffer();}catch{fail('Choose a supported image (JPEG, PNG or WebP)');}
  res.json(await tx(async c=>{const a=await owned(c,req.params.id,req.user.id,true);if(a.status==='submitted')fail('Assignment is submitted',409);if(!a.steps.some(s=>s.id===req.params.step))fail('Step not found',404);const n=(await c.query('SELECT count(*)::int AS n FROM testing_evidence WHERE assignment_id=$1 AND step_id=$2',[a.id,req.params.step])).rows[0].n;if(n>=5)fail('Maximum five photos per step');return (await c.query('INSERT INTO testing_evidence(assignment_id,step_id,photo) VALUES($1,$2,$3) RETURNING id,assignment_id,step_id,created_at',[a.id,req.params.step,photo])).rows[0];}));
 }));
 app.get('/api/testing/evidence/:id',requireAuth,route(async(req,res)=>{const r=(await pool.query("SELECT e.photo FROM testing_evidence e JOIN testing_assignments a ON a.id=e.assignment_id WHERE e.id=$1 AND (a.user_id=$2 OR $3)",[req.params.id,req.user.id,canManage(req.user)])).rows[0];if(!r)fail('Photo not found',404);res.set('Cache-Control','private, no-store').type('image/jpeg').send(r.photo);}));
 app.get('/api/testing/people',requireTestingManager,route(async(req,res)=>res.json((await pool.query('SELECT id,name,email,active,is_tester FROM users WHERE active=true ORDER BY name,id')).rows)));
 app.get('/api/admin/testing-assignments',requireTestingManager,route(async(req,res)=>res.json(await enrich((await pool.query('SELECT a.*,u.name AS user_name,u.email AS user_email FROM testing_assignments a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.updated_at DESC,a.id DESC')).rows))));
 app.get('/api/admin/testing/templates',requireTestingManager,route(async(req,res)=>res.json((await pool.query('SELECT * FROM testing_templates ORDER BY created_at DESC,id DESC')).rows)));
 app.post('/api/admin/testing/templates',requireTestingManager,route(async(req,res)=>{const b=validateDraft(req.body);res.json((await pool.query('INSERT INTO testing_templates(title,title_es,summary,summary_es,edition,steps,assignee_ids) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[b.title,b.title_es,b.summary,b.summary_es,b.edition,JSON.stringify(b.steps),JSON.stringify(b.assignee_ids)])).rows[0]);}));
 app.put('/api/admin/testing/templates/:id',requireTestingManager,route(async(req,res)=>{const b=validateDraft(req.body);const r=(await pool.query("UPDATE testing_templates SET title=$1,title_es=$2,summary=$3,summary_es=$4,edition=$5,steps=$6,assignee_ids=$7,revision=revision+1 WHERE id=$8 AND status='draft' AND revision=$9 RETURNING *",[b.title,b.title_es,b.summary,b.summary_es,b.edition,JSON.stringify(b.steps),JSON.stringify(b.assignee_ids),req.params.id,req.body.revision])).rows[0];if(!r)fail('Draft changed or is already published. Reload before editing.',409);res.json(r);}));
 app.post('/api/admin/testing/templates/:id/publish',requireTestingManager,route(async(req,res)=>{res.json(await tx(async c=>{const t=(await c.query('SELECT * FROM testing_templates WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!t)fail('Draft not found',404);if(t.status==='published')return {ok:true,already_published:true};if(t.revision!==req.body.revision)fail('Draft changed. Review it again before publishing.',409);if(!t.title_es||!t.summary_es||t.steps.some(s=>!s.title_es||!s.instruction_es))fail('Complete the Spanish title, instructions and steps before publishing');if(!t.assignee_ids.length)fail('Select at least one tester');const users=(await c.query('SELECT * FROM users WHERE id=ANY($1::int[]) FOR UPDATE',[t.assignee_ids])).rows;if(users.length!==t.assignee_ids.length||users.some(u=>!u.active))fail('Select active tester accounts');const missing=users.filter(u=>!editionAccess(u).includes(t.edition));if(missing.length)fail('Enable this version in Admin user access first: '+missing.map(u=>u.name||u.email).join(', '));
  for(const u of users){await c.query(`INSERT INTO testing_assignments(assignment_key,assignee_name,assignee_email,user_id,title,title_es,summary,summary_es,steps,edition,template_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[`template-${t.id}-user-${u.id}`,u.name||u.email,u.email,u.id,t.title,t.title_es,t.summary,t.summary_es,JSON.stringify(t.steps),t.edition,t.id]);await c.query('UPDATE users SET is_tester=true WHERE id=$1',[u.id]);}
  await c.query("UPDATE testing_templates SET status='published',published_at=now(),revision=revision+1 WHERE id=$1",[t.id]);return {ok:true,assigned:users.length};}));}));
 app.post('/api/admin/testing-assignments/:id/review',requireTestingManager,route(async(req,res)=>{if(!['pending','reviewed','retest_requested'].includes(req.body.review_status))fail('Invalid review status');const notes=str(req.body.review_notes||'',4000);res.json(await tx(async c=>{const a=(await c.query('SELECT * FROM testing_assignments WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!a)fail('Assignment not found',404);if(a.revision!==req.body.revision)fail('Results changed. Refresh before reviewing.',409);if(req.body.review_status==='retest_requested'&&!notes)fail('Explain what needs retesting');return (await c.query("UPDATE testing_assignments SET review_status=$1,review_notes=$2,status=CASE WHEN $1='retest_requested' THEN 'in_progress' ELSE status END,submitted_at=CASE WHEN $1='retest_requested' THEN NULL ELSE submitted_at END,seen_at=CASE WHEN $1='retest_requested' THEN NULL ELSE seen_at END,revision=revision+1,updated_at=now() WHERE id=$3 RETURNING *",[req.body.review_status,notes,a.id])).rows[0];}));}));
 app.get('/api/testing/assignments/:id/history',requireAuth,route(async(req,res)=>{const a=(await pool.query('SELECT id FROM testing_assignments WHERE id=$1 AND (user_id=$2 OR $3)',[req.params.id,req.user.id,canManage(req.user)])).rows[0];if(!a)fail('Assignment not found',404);res.json((await pool.query('SELECT id,snapshot,created_at FROM testing_submissions WHERE assignment_id=$1 ORDER BY id DESC',[a.id])).rows);}));
 app.get('/api/testing/assignments/:id/download',requireAuth,route(async(req,res)=>{const row=(await pool.query('SELECT * FROM testing_assignments WHERE id=$1 AND (user_id=$2 OR $3)',[req.params.id,req.user.id,canManage(req.user)])).rows[0];if(!row)fail('Assignment not found',404);const [a]=await enrich([row]),es=req.query.lang==='es',pick=(o,k)=>es&&o[k+'_es']?o[k+'_es']:o[k];const labels=es?{not_tested:'Sin probar',passed:'Pasó',failed:'Falló',blocked:'Bloqueado'}:{not_tested:'Not Tested',passed:'Passed',failed:'Failed',blocked:'Blocked'};res.set('Cache-Control','private, no-store').set('Content-Disposition',`attachment; filename="testing-assignment-${a.id}-${es?'es':'en'}.pdf"`).type('application/pdf');const doc=new PDFDocument({margin:45});doc.pipe(res);doc.fillColor('#000').font('Helvetica-Bold').fontSize(18).text(pick(a,'title'));doc.font('Helvetica').fontSize(11).moveDown().text(`${a.assignee_name} | ${a.device||''}`).text(pick(a,'summary')||'').moveDown();for(const [n,s] of a.steps.entries()){if(doc.y>640)doc.addPage();doc.font('Helvetica-Bold').text(`${n+1}. ${pick(s,'title')}`);doc.font('Helvetica').text(pick(s,'instruction')).text(labels[a.results[s.id]?.status||'not_tested']).text(a.results[s.id]?.notes||'');const ids=a.issues.filter(i=>i.testing_step_id===s.id).map(i=>'#'+i.id);if(ids.length)doc.text((es?'Reportes: ':'Issues: ')+ids.join(', '));doc.moveDown();}doc.text(a.tester_notes||'').moveDown().text(a.review_notes||'');doc.end();}));
}
module.exports={initTestingHub,registerTestingHub,validateDraft,validateResults,counts};
