import fs from 'node:fs';
const id=Number(process.env.ISSUE_ID);
if(!Number.isInteger(id)||id<1)throw new Error('Invalid issue ID');
if(!process.env.OPENAI_API_KEY||!process.env.TESTER_QUEUE_TOKEN)throw new Error('Cloud repair credentials are not configured');
const r=await fetch('https://photonotesapp.com/api/automation/testing-queue',{headers:{authorization:`Bearer ${process.env.TESTER_QUEUE_TOKEN}`},signal:AbortSignal.timeout(15000),redirect:'error'});
if(!r.ok)throw new Error(`Queue returned ${r.status}`);
const i=(await r.json()).issues.find(i=>i.id===id);
if(!i||!['new','reviewing','fixing'].includes(i.management_status)||i.repair_lease_until&&new Date(i.repair_lease_until)>new Date())throw new Error('Report is not available for cloud investigation');
const evidence=JSON.stringify({id,description:i.description,page_name:i.page_name,edition:i.reported_edition,viewport:i.viewport,reporter_details:i.reporter_details});
fs.appendFileSync(process.env.GITHUB_OUTPUT,`evidence=${evidence}\n`);
